M48
; DRILL file {KiCad 7.0.7} date Mon Sep 11 14:58:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-11T14:58:09+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.4Y-3.7
X4.4Y-4.3
X6.0Y-3.7
X6.0Y-4.3
T2
X4.3Y-3.4
X7.8Y-3.0
X7.8Y-4.9
T0
M30
